# Server Port
server:
  port: 8080

spring:
  cloud:
    consul:
      enabled: false
    gateway:
      # Discovery Locator
      discovery:
        locator:
          enabled: false
      # Routes
      routes:
        - id: graph-network-command
          uri: lb://graph-network-command
          predicates:
            - Path=/graph-network
            - Method=POST,PUT
