# Server Port
server:
  port: 8080

spring:
  cloud:
    consul:
      enabled: false
    gateway:
      # Discovery Locator
      discovery:
        locator:
          enabled: true
      # Routes
      routes:
        - id: network-elements
          uri: lb://network-elements
          predicates:
            - Path=/api/**
            - Method=GET,POST,PUT,DELETE