version: '3.9'

services:
  api-gateway:
    image: lsefiane/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - ${GATEWAY_HOST_PORT}:8080
    depends_on:
      - consul-server
      - network-elements
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_CLOUD_CONSUL_ENABLED: ${SPRING_CLOUD_CONSUL_ENABLED}
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CLOUD_CONSUL_PORT: ${SPRING_CLOUD_CONSUL_PORT}
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED}
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWERCASESERVICEID: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWERCASESERVICEID}
      SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER}
      SPRING_CLOUD_CONSUL_DISCOVERY_REGISTERHEALTHCHECK: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTERHEALTHCHECK}
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: ${SPRING_CLOUD_GATEWAY_ROUTES_0_ID}
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI}
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: ${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0}
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[1]: ${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_1}
      SPRING_CLOUD_GATEWAY_ROUTES_[0]_METADATA_CORS_ALLOWEDORIGINS: ${SPRING_CLOUD_GATEWAY_ROUTES_0_METADATA_CORS_ALLOWEDORIGINS}
      SPRING_CLOUD_GATEWAY_ROUTES_[0]_METADATA_CORS_ALLOWEDMETHODS: ${SPRING_CLOUD_GATEWAY_ROUTES_0_METADATA_CORS_ALLOWEDMETHODS}
      SPRING_CLOUD_GATEWAY_ROUTES_[0]_METADATA_CORS_ALLOWEDHEADERS: ${SPRING_CLOUD_GATEWAY_ROUTES_0_METADATA_CORS_ALLOWEDHEADERS}

      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: ${SPRING_CLOUD_GATEWAY_ROUTES_1_ID}
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI}
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: ${SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0}
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_1: ${SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_1}
      SPRING_CLOUD_GATEWAY_ROUTES_1_METADATA_CORS_ALLOWEDORIGINS: ${SPRING_CLOUD_GATEWAY_ROUTES_1_METADATA_CORS_ALLOWEDORIGINS}
      SPRING_CLOUD_GATEWAY_ROUTES_1_METADATA_CORS_ALLOWEDMETHODS: ${SPRING_CLOUD_GATEWAY_ROUTES_1_METADATA_CORS_ALLOWEDMETHODS}
      SPRING_CLOUD_GATEWAY_ROUTES_1_METADATA_CORS_ALLOWEDHEADERS: ${SPRING_CLOUD_GATEWAY_ROUTES_1_METADATA_CORS_ALLOWEDHEADERS}
    networks:
      - gateway
      - consul

networks:
  gateway:
  consul:
