version: '3.9'
services:
  redis-node-0:
    image: bitnami/redis-cluster:7.0
    container_name: redis-node-0
    expose:
      - 6379
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: ${REDIS_NODES}
    networks:
      - redis

  redis-node-1:
    image: bitnami/redis-cluster:7.0
    container_name: redis-node-1
    expose:
      - 6379
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: ${REDIS_NODES}
    networks:
      - redis

  redis-node-2:
    image: bitnami/redis-cluster:7.0
    container_name: redis-node-2
    expose:
      - 6379
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: ${REDIS_NODES}
    networks:
      - redis

  redis-node-3:
    image: bitnami/redis-cluster:7.0
    container_name: redis-node-3
    expose:
      - 6379
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: ${REDIS_NODES}
    networks:
      - redis

  redis-node-4:
    image: bitnami/redis-cluster:7.0
    container_name: redis-node-4
    expose:
      - 6379
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: ${REDIS_NODES}
    networks:
      - redis

  redis-node-5:
    image: bitnami/redis-cluster:7.0
    container_name: redis-node-5
    expose:
      - 6379
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: ${REDIS_NODES}
      REDISCLI_AUTH: ${REDISCLI_AUTH}
      REDIS_CLUSTER_REPLICAS: ${REDIS_CLUSTER_REPLICAS}
      REDIS_CLUSTER_CREATOR: ${REDIS_CLUSTER_CREATOR}
    networks:
      - redis

volumes:
  redis-cluster_data-0:
  redis-cluster_data-1:
  redis-cluster_data-2:
  redis-cluster_data-3:
  redis-cluster_data-4:
  redis-cluster_data-5:

networks:
  redis: