version: '3.9'

services:
  graph-network-command:
    image: lsefiane/graph-network-command:latest
    container_name: graph-network-command
    restart: unless-stopped
    ports:
      - ${GRAPH_NETWORK_COMMAND_CONTAINER_PORT}
    depends_on:
      - consul-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_CLOUD_CONSUL_ENABLED: ${SPRING_CLOUD_CONSUL_ENABLED}
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CLOUD_CONSUL_PORT: ${SPRING_CLOUD_CONSUL_PORT}
      SERVER_SERVLET_CONTEXT_PATH: ${SERVER_SERVLET_CONTEXT_PATH}
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: ${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
      SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH}
    networks:
      - graph
      - consul

networks:
  graph:
  consul: