version: '3.9'
services:
  network-elements-db:
    image: postgres:latest
    container_name: network-elements-db
    restart: unless-stopped
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-elements

  flyway:
    image: lsefiane/flyway:latest
    container_name: flyway
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    environment:
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_URL: ${POSTGRES_URL}
    depends_on:
      - network-elements-db
    networks:
      - network-elements

  network-elements:
    image: lsefiane/network-elements:latest
    container_name: network-elements
    restart: unless-stopped
    expose:
      - ${NETWORK_ELEMENTS_PORT}
    healthcheck:
      test: wget --no-verbose --spider http://localhost:8080/network-elements/api/actuator/health || exit 1
      interval: 25s
      timeout: 3s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_INITIALIZATION_MODE: ${SPRING_DATASOURCE_INITIALIZATION_MODE}
      SPRING_CLOUD_CONSUL_ENABLED: ${SPRING_CLOUD_CONSUL_ENABLED}
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CLOUD_CONSUL_PORT: ${SPRING_CLOUD_CONSUL_PORT}
      SERVER_SERVLET_CONTEXT_PATH: ${SERVER_SERVLET_CONTEXT_PATH}
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: ${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
      SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH}
      SPRING_APPLICATION_NAME: ${SPRING_NETWORK_ELEMENTS_APPLICATION_NAME}
      SPRING_CACHE_TYPE: ${SPRING_CACHE_TYPE}
      SPRING_REDIS_CLUSTER_NODES: ${SPRING_REDIS_CLUSTER_NODES}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
      SPRING_REDIS_CLUSTER_MAX_REDIRECTS: ${SPRING_REDIS_CLUSTER_MAX_REDIRECTS}
      SPRING_REDIS_POOL_MAX_IDLE: ${SPRING_REDIS_POOL_MAX_IDLE}
      SPRING_REDIS_POOL_MIN_IDLE: ${SPRING_REDIS_POOL_MIN_IDLE}
      SPRING_REDIS_POOL_MAX_ACTIVE: ${SPRING_REDIS_POOL_MAX_ACTIVE}
      SPRING_REDIS_POOL_MAX_WAIT: ${SPRING_REDIS_POOL_MAX_WAIT}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
      KAFKA_TOPIC_PARTITIONS: ${KAFKA_TOPIC_PARTITIONS}
      KAFKA_TOPIC_REPLICAS: ${KAFKA_TOPIC_REPLICAS}
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: ${SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL}
    depends_on:
      - network-elements-db
      - consul-server
      - redis-node-5
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    networks:
      - network-elements
      - consul
      - kafka
      - schema-registry
      - redis


volumes:
  pgdata:

networks:
  network-elements:
  consul:
  kafka:
  schema-registry:
  redis: