version: '3.9'
services:
  network-graph:
    image: lsefiane/network-graph:latest
    container_name: network-graph
    restart: unless-stopped
    expose:
      - ${NETWORK_GRAPH_PORT}
    depends_on:
      - consul-server
      - redis-node-5
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    environment:
      LISTEN_AUTO_START: ${LISTEN_AUTO_START}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPECIFIC_AVRO_READER: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPECIFIC_AVRO_READER}
    networks:
      - network-graph
      - network-elements
      - consul
      - kafka
      - schema-registry
      - redis

networks:
  network-graph:
  network-elements:
  consul:
  kafka:
  schema-registry:
  redis: